name: Main retail_chain workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: "pip"
      - name: Install dependencies lint
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lint.txt
      - name: Run linter
        run: python -m flake8 .
      - name: Run isort
        run: python -m isort --check-only .

  tests:
    needs: lint
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: 'pip'
      - name: Install dependencies test
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Run Django tests
        env:
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_password
          POSTGRES_DB: django_db
          DB_HOST: 127.0.0.1
          DB_PORT: 5432
          SECRET_KEY: DJANGO_SECRET_KEY
        run: python manage.py test